### ISSUE TITLE
Exposing `Marker` in `Yaml`

### ISSUE THREAD

**Issue by felipesere** [Ethiraric/yaml-rust2#27]
This might be a bit controversial, but it would be very helpful if the `Marker` type was exposed on the various Nodes of YAML.

My intended use-case it to load a YAML file, search for certain patterns, and report them back to the users.
Basically a linter for some custom helm charts and similar files 😅 
At the moment I print `jq-like` paths to issues because once I go through serde I loose access to rows and columns.

If I had access to them, I could for example print nice snippets or even highlight them on GitHub.

Would this be a feature that is better placed in `sephyr`?

**Comment by Ethiraric** [comment]
This is indeed out of the scope of this repository as it would require huge changes to how the `Yaml` object is constructed.

This could be a contribution to `saphyr`. If you need markers, you unfortunately (for now) need to go through the low-level parsing API.

**Comment by yannham** [comment]
I'm interested in this feature as well. As I see it, we would have to duplicate the `Yaml` struct to have position information at every node, and duplicate `YamlLoader` (or not necessarily duplicate; we might be able to make it generic) to store this information. Given the size of those structures though, it doesn't look like a huge change either. Would you be open to such a PR to saphyr @Ethiraric ? I think I'll first try to do it on my side for the [Nickel](https://github.com/tweag/nickel/) project, but I'm eager to upstream it if it's useful.

**Comment by Ethiraric** [comment]
Github still doesn't let me transfer the issue to  `saphyr` for some reason. 

You may go ahead and implement this and create a Pull Request there. Adding this was initially the reason I started working on `yaml-rust`. 

I have to say I don't like having to duplicate the `Yaml` structure. There's also another feature that was requested (support for storing and re-emitting comments) and would have needed to duplicate it. 

I'd like to avoid having a bare object, one with markers, one with comments and another one with both (and all the duplicated methods and trait implementations associated). I'm however unsure if that is possible without heavily impacting memory usage for people who do not need these.

**Comment by yannham** [comment]
I understand. I'll see if I can work something out. You might pay the price with generics or a bit of internal boilerplate but it should be doable with a recursion-scheme like approach, with a YAML type generic in its "recursive" occurences, like `enum YamlF<T> { Array(Vec<T>), Map(Map<String, T>), ...}` and then instantiating `Yaml = YamlF<Yaml>` and `YamlSpanned = { span: Span, node: YamlF<YamlSpanned> }` or something. At least that what's we do in Nickel avoid duplicating different flavours of the same AST but with different metadata.

**Comment by Ethiraric** [comment]
That is surprisingly simple yet efficient. I had never thought about it. I should be able to do it if you don't want to. That shouldn't take me much time.

**Comment by yannham** [comment]
It's up to you, I'm eager to do it because I know OSS maintainer time isn't infinite and I need this feature, but if you have the bandwidth and want to try it by yourself, fine by me! It's not very urgent for me and I can always do it locally if I need it before it's upstreamed.

**Comment by Ethiraric** [comment]
That is very thoughtful of you, thank you ❤️ 

I should be able to get it done in a few hours of work. I think this should overall save us a bit of time since I already know the code well. 

I should have time to implement that by the end of the week if that's okay with you. Would spare you from having to implement it maybe.

**Comment by felipesere** [comment]
I had a stab at an extremely basic variation of this here https://github.com/saphyr-rs/saphyr/pull/5
Mostly to see if it would do what I needed it do 😅

I like the idea of having multiple impls for spans and comments.
Alternative suggestion: have a `Context` struct that has optional location and comments?

**Comment by yannham** [comment]
> I should have time to implement that by the end of the week if that's okay with you. Would spare you from having to implement it maybe.

Works for me. Thanks for looking into that!.

>  Alternative suggestion: have a Context struct that has optional location and comments?

Yes, this is another trade-off which avoids generics (which is the drawback of the recursion-scheme approach that I described). However I believe @Ethiraric mentioned that he doesn't want to pay the memory price when parsing normally without locations (or comments), which would be the case with `Context`...  (while the `type Yaml = YamlF<Yaml>` should be strictly equivalent to the current definition)

**Comment by felipesere** [comment]
Would you pay for it locations and comments were behind options?

**Comment by yannham** [comment]
Well, you still pay for the option, and you also still need an additional indirection. Take a simple YAML-like AST:

```rust
enum Object{
  Number(i64),
  String(String),
  Array(Vec<Object>),
  Map(HashMap<String, Object>),
}
```

Now, if you want to add context, you need to do something like the following:

```rust
struct Object {
  data: ObjectData,
  span: Option<Span>,
  comment: Option<String>,
}

enum ObjectData {
  Number(i64),
  String(String),
  Array(Vec<Object>),
  Map(HashMap<String, Object>),
}
```

Now, you've added _for each node of the AST_: 2 options (whether they're `None` or not doesn't matter, they still take up a  pointer size worth of memory each), and you've also added one indirection at each level. An array, instead of storing directly the data, now stores a structure `Object` that has a pointer to the underlying enum. Whether this is acceptable is up to you and your use-case, but following Rust's philosophy, I can understand, as a library author, why you wouldn't want to impose this cost to users that just want to deserialize programmatically and don't care about either location or comments.

The recursion schemes-based approach, on the other hand, instantiate some kind of generic template `ObjectF` to two different types _at compile time_. So somehow you get two "specialized" version, and the one without context doesn't have any additional stuff to carry.

**Comment by Ethiraric** [comment]
Outside of the unconditional added size that a `Context` structure would require, there's another drawback that I don't really like, which is that the `Options` it adds add potentially unnecessary calls to `unwrap`. If I take as example @yannham's code above, the `ObjectData` is always the same type and isn't specialized based on what added information were requested upon parsing. If we add generics and/or traits to the `Yaml` object, we can engrave in the type system those information and relying on an information that wasn't request upon parsing results in a compile-time type error rather than a runtime error.

**Comment by Ethiraric** [comment]
Do you think it makes more sense to have:

```rs
// T represents metadata. They'd be a tuple, I guess.
enum Yaml<T> {
  Real(String, T),
  //...
}
```

Or
```rs
// T represents metadata. They'd be a tuple, I guess.
struct AnnotatedYaml<T> {
  pub metadata: T,
  pub node: Yaml,
}
```

In either case, I'd probably use structures (`AnnotatedYaml<Marker>` would for instance add markers) and traits so that if a structure passed in the generic has a certain trait (say `AnnotateMarker`), then the loader would add the marker.
Similarly, if an `AnnotatedYaml` has a generic with `AnnotateMarker`, it'd implement another trait which would return the marker.

On the plus side of the first implementation is that there is no need to re-define all `Yaml` methods since we'd operate on the same structure.
However, it changes the enum for default parses (those where no metadata is requested), adding an extra `_` or `..` to every enum variant in any `match`.

The second implementation would be much more verbose to use (adding multiple `.node` for traversal) but lets the client code for people already using the library unchanged.

Or maybe I'm just overcomplicating everything.

**Comment by yannham** [comment]
Both have pros and cons. I think I prefer the `AnnotatedYaml` one, although it adds an indirection, because the other is repeating metadata everywhere (at each leaf node), which is a bit annoying IMHO - often when looking at the leaf you don't care about the span. They are better separated in a struct with position + actual structure.

Now I realize that you can't really do `pub type Yaml = YamlF<Yaml>`, you need a struct, box or whatever as an indirection. I think in my case I had to put a `Box` anyway (not for YAML but where I used this trick), in order to make the initial type properly sized, but in your case you might not want to do that... The best you can do is `pub struct Yaml(YamlF<Yaml>)`, which does add an indirection (I mean, not at runtime, but in terms of API). Something like:

```rust
pub enum YamlF<T> {
    Real(String),
    Integer(i64),
    String(String),
    Boolean(bool),
    Array(ArrayF<T>),
    Hash(HashF<T>),
    Alias(usize),
    Null,
    BadValue,
}

pub type ArrayF<T> = Vec<T>;
pub type HashF<T> = LinkedHashMap<T, T>;

pub struct Yaml { data: YamlF<Yaml> };
pub type Array = ArrayF<Yaml>;
pub type Hash = ArrayF<Yaml>;

// This one is only if you need span
pub struct SpannedYaml {
  data: YamlF<SpannedYaml>,
  span: std::ops::Range<usize>,
}

pub type SpannedArray = ArrayF<SpannedYaml>;
pub type SpannedHash = HashF<SpannedYaml>;

// You can implement non-recursive methods in a generic way
impl<T> YamlF<T> {
  // gives both yaml.data.is_null() and spanned_yaml.data.is_null()
  pub fn is_null(&self) -> bool {
    matches!(*self, YamlF::Null)
  }

   // ...
}
```

Personally, I don't find that turning `match yaml_value` to `match yaml_value.data` is that big of an issue as a consumer of the library, and it also requires to change only one line in a match. On the other hand, if your match is looking at each and every case, with solution 1, you have to patch _each pattern_ instead. That being said, both representations are isomorphic, and this is also a matter of taste.

**Comment by Ethiraric** [comment]
> Now I realize that you can't really do pub type Yaml = YamlF<Yaml>,
I could do that. The indirection is through the `Vec` and the `HashMap`.

> IMHO - often when looking at the leaf you don't care about the span. They are better separated in a struct with position + actual structure
Now that you mention it, I agree with that. It wasn't obvious to me, though.

**Comment by felipesere** [comment]
>  because the other is repeating metadata everywhere (at each leaf node), which is a bit annoying IMHO - often when looking at the leaf you don't care about the span

Not sure about this.  I'll be parsing Kubernetes manifests, Helm values.yaml and likely some CI yaml and I want to highlight individual bits and bobs. E.g. a specific annotation in some spec. In that case I'd want to have access to the start/end of each key along the the path as well as the actual annotation. 
Particularly the last one would be a leaf node, right?

**Comment by Ethiraric** [comment]
I interpreted that as "each leaf node of the `Yaml` enum" rather than "each leaf node of the YAML parse tree".

The underscores in
```rs
pub enum Yaml {
  String(String, _),
  Real(String, _),
  Array(Array, _),
  // ...
}
```

**Comment by yannham** [comment]
Right, sorry if that wasn't very clear - both propositions would actually encode exactly the same information, which is to put span everywhere, both at leafs (strings, reals, etc.) and containers (objects and arrays). But with proposition 1., the span is pushed down each enum variant, which means that if you pattern match the whole Yaml tree you have to ignore them in a lot of places:

```rust
match my_yaml_value {
  String(s, _) => format!("string {s}"),
  Real(s, _) => "format!("real {s}"),
  Array(array, _) => do_something_with_array(array),
 ...etc...
}
```

with proposition 2, you'd do instead:

```rust
match my_yaml_value.data {
  String(s) => format!("string {s}"),
  Real(s) => "format!("real {s}"),
  Array(array) => do_something_with_array(array),
 ...etc...
}
```

You can still extract the span at every node with `my_yaml_data.span`.

**Comment by Ethiraric** [comment]
I ended up separating both implementations. It's a bit of code duplication, but I think we should be mostly ok with that.

It has required a lot of modifications anyway to support the `Index` `impl`s which had trouble understanding that `Self` is the type of the `Node` and `Node` is the type of `Self`, but I got it to compile in the end.

As is customs, this feature ends up being much more difficult to support properly. I am one day late to work on it, and I'll likely be several days late delivering it. The commit for setting up the annotated `Yaml` enum is [here](https://github.com/saphyr-rs/saphyr/commit/e80d73cacf77dfd1a711d67434eb1d5ef7263a2c). Constructive criticism is always appreciated.

**Comment by yannham** [comment]
> I ended up separating both implementations. It's a bit of code duplication, but I think we should be mostly ok with that.

I agree, it's a reasonable choice (and what I planned initially, actually, to have just two specialized types), especially for a library - it puts the burden of duplication on the maintainers but makes for a better user interface.

> Constructive criticism is always appreciated.

Looks good to me, as far as I can tell. I'm for using macros very sparingly, but I think it's ok here - repetitive code, easy to understand what the macros do, and it doesn't hurt the user-facing documentation (in fact I didn't even know that macros could substitute within the docstring part as well, so today I learned!)

**Comment by Ethiraric** [comment]
This will not be implemented in `yaml-rust2`, but is rather an objective for [`saphyr`](https://github.com/saphyr-rs/saphyr).
