### ISSUE TITLE
[Bug] Cannot parse YAML file from Sublime Packages

### ISSUE THREAD

**Issue by SleeplessOne1917** [Ethiraric/yaml-rust2#29]
I get an error when trying to parse [this file from Sublime Packages](https://github.com/sublimehq/Packages/blob/fa6b8629c95041bf262d4c1dab95c456a0530122/Markdown/Markdown.sublime-syntax). When I try to do so, I get this error:

`Err(ScanError { mark: Marker { index: 21883, line: 447, col: 18 }, info: "while scanning a block scalar, did not find expected comment or line break" })`

It also breaks when trying to parse [this file](https://github.com/sublimehq/Packages/blob/fa6b8629c95041bf262d4c1dab95c456a0530122/Makefile/Makefile.sublime-syntax) because it doesn't like comments appearing between the `%YAML 1.2` and the 3 hyphens.

I discovered this issue when [updating the `syntect` library to use `yaml-rust2` instead of `yaml-rust`](https://github.com/trishume/syntect/pull/544). Everything was parsed fine on version 0.4.5 of the old `yaml-rust` library. 

This is unfortunately the only useful info on the bug I have at the moment.

**Comment by Ethiraric** [comment]
Regarding the Markdown file, it has to do with indentation. I tried trimming down the file and for some reason it breaks if the indent is 18 cols or higher. I most definitely messed something up when trying to optimize indentation scanning. I'll have a look tomorrow; I just had time for a quick check to see if it was an easy fix.

The issue with the Makefile file was fixed in 0eb7936, although I cannot remember whence that issue was brought to my knowledge. A release has not yet been made with that commit. I think I'll fix this and release afterwards.

**Comment by Ethiraric** [comment]
The issue has been fixed and a new release has been tagged! :)
Both files should now be parsed properly. Please do let me know if you still encounter any bug!

**Comment by Ethiraric** [comment]
@tranzystorekk this should be of interest to you. The bug you mentioned in https://github.com/Ethiraric/yaml-rust2/issues/21#issuecomment-2053513507 should be fixed.

**Comment by tranzystorekk** [comment]
Thank you!
