### ISSUE TITLE
unable to parse bracket multiline sequence

### ISSUE THREAD

**Issue by naskya** [Ethiraric/yaml-rust2#30]
A yaml sequence with square brackets may have line breaks in the middle ([js-yaml demo](https://nodeca.github.io/js-yaml/#yaml=Zm9vOiBbCiAgJ2EnLAogICdiJywKICAnYycsCl0=)):
```yaml
foo: [
  'a',
  'b',
  'c',
]
```

`yaml-rust` and `serde_yaml` can parse this sequence, but `yaml-rust2` fails ([example test code](https://github.com/naskya/yaml-parse-example/blob/57d96203e2324544878916d0009814eeab155014/src/lib.rs)):
- [`yaml-rust` result](https://github.com/naskya/yaml-parse-example/actions/runs/9635604476/job/26572557354)
- [`yaml-rust2` result](https://github.com/naskya/yaml-parse-example/actions/runs/9635604473/job/26572557352)
- [`serde_yaml` result](https://github.com/naskya/yaml-parse-example/actions/runs/9635604474/job/26572557364)

Unless I am missing something, I think this is a regression introduced after the fork.

Nonetheless, thank you for maintaining this project. I really appreciate your work!

**Comment by Ethiraric** [comment]
The YAML you provided is not compliant with the specification. The reference parser [here](https://play.yaml.io/main/parser?input=Zm9vOiBbCiAgJ2EnLAogICdiJywKICAnYycsCl0=) fails parsing it. `yaml-rust`, `serde_yaml` and `js-yaml` should all reject that input.

The issue here lies not within the linebreaks, but with the closing square bracket. The closing square bracket must be indented at least as far as the contents. The following would be the [correct syntax](https://play.yaml.io/main/parser?input=Zm9vOiBbCiAgJ2EnLAogICdiJywKICAnYycsCiAgXQ==):

```yaml
foo: [
  'a',
  'b',
  'c',
  ]
```

**Comment by naskya** [comment]
Thanks for the quick and clear response, and I’m sorry to bother you with an invalid report.

Please keep your great work!

**Comment by Ethiraric** [comment]
No worry at all! I'd rather you report this and it ends up as being invalid, rather that you don't and it ends up being a real issue ;)

Thank you for your kind words! <3 Very much appreciated!
