### ISSUE TITLE
[Feature request] Sourcemap support

### ISSUE THREAD

**Issue by felamaslen** [Ethiraric/yaml-rust2#38]
It would be really great to be able to keep track of line/column information for each token, in the yaml lexer (`scanner.rs`).

One use case is if you are validating YAML against a JSON schema. If you get errors in the outputted JSON string, it would be nice to be able to map the errors' locations to those in the YAML document, for example to apply automatic fixes.

I haven't looked too deeply into it, but I suspect we could add a `Span` (with `hi` and `lo` line/columns, i.e. a range) field to the `Token` struct, and expose this in the `parser` (via the lexer) when fetching the next token. We could expose a public API on the `Yaml` struct to look up a `Span` based on a path (e.g. `object.items[3].key`).

**Comment by Ethiraric** [comment]
Hi!
This is currently worked on, but not on `yaml-rust2`. This repository is meant as just a replacement for `yaml-rust`, with a best-effort in terms of optimizations.
Bug reports will be fixed, but new features won't be added.

It is not production-ready, but you can have a look at [`saphyr`](https://github.com/saphyr-rs/saphyr) and [`saphyr-parser`](https://github.com/saphyr-rs/saphyr-parser). The latter probably already has the features you need (although you may have to use a specific commit instead of a release).
